# Generated by Django 5.1.3 on 2024-12-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_comment_author_alter_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='subcategory',
            new_name='subcategory_id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='active',
        ),
    ]
