# Generated by Django 5.1.3 on 2024-12-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_category_article_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
    ]
