# Generated by Django 5.1.3 on 2024-12-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_comment_article_comment_article_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article_id',
            new_name='article',
        ),
    ]
