# Generated by Django 5.1.3 on 2024-12-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_article_id_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
